### ISSUE TITLE
Histogram of random variables

### ISSUE THREAD

**Issue by csantosb** [fvutils/pyvsc#5] opened 2020-06-01 18:19 UTC
Hi,

  Thanks for this great library, I just discovered. Really useful.

  I've been performing some tests on the outcomes one may get out of this just to check I understand the documentation correctly. You may see it [here](https://gitlab.com/ip-vhdl/pyvsc-test/-/blob/master/test.py).

  As you can see, it's just creating random data and histogramming it. From the results
[here](https://gitlab.com/ip-vhdl/pyvsc-test/-/jobs/576046746), I observe that constraining the variables makes the histogram weird. What am I doing wrong ?

Thanks !

**Comment by mballance** [comment] 2020-06-02 01:05
Hi Cayetano,
    Thank you for the feedback and creating a testcase (very helpful!).
I'll certainly investigate further and let you know what I find. At this
point, I wouldn't necessarily conclude that you're doing anything wrong.
    I would like to have the option of including an abstracted version of
the testcase in the PyVSC test suite. I see that the file doesn't have a
license header. Is it okay if I include code from this test in the
Apache-licensed PyVSC package?

Thanks and Best Regards,
Matthew

**Comment by csantosb** [comment] 2020-06-02 14:40
Sure, feel free to use this code. It's nothing but a simple means of doing some testing on you lib.

**Comment by mballance** [comment] 2020-06-03 00:24
Okay, so some good news and (maybe) bad news. I'm able to reproduce the issue, and it actually appears that a project I already had underway to determine the rough actual domain of variables based on constraint expressions will really help with randomness. After applying these changes, here are the histograms I'm seeing for the first three variables:
self.rand_bit_1 histogram is: [95, 105, 118, 103, 129, 116, 120, 106, 108]
self.rand_bit_2 histogram is: [29, 40, 48, 37, 28, 37, 30, 37, 33, 31, 32, 28, 36, 35, 40, 29, 38, 25, 42, 38, 32, 23, 31, 35, 41, 35, 33, 37, 40]
self.rand_bit_3 histogram is: [15, 11, 17, 20, 16, 13, 12, 20, 14, 22, 13, 20, 14, 14, 19, 13, 10, 13, 18, 8, 16, 15, 19, 12, 21, 24, 16, 13, 18, 13, 19, 18, 13, 22, 15, 15, 15, 12, 18, 22, 10, 14, 14, 12, 17, 20, 14, 14, 22, 14, 11, 18, 11, 12, 14, 12, 13, 11, 10, 18, 23, 15, 10, 15, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Clearly, not perfect yet (especially on the third), but getting better. 
I'm still working on resolving the last few bugs with this, so it will be a bit (~week or so) before this will be available. 

Thanks again for raising this issue!

Best Regards,
Matthew

**Comment by mballance** [comment] 2020-06-06 17:26
Hi Cayetano,
    Okay, after a bit more work things are looking quite good. The work I had been doing to account for the impact of top-level constraints on reachable domains seems to be resulting in much-better distributions on constrained variables. This code is now available in the Git repository, and available as a 0.0.2 release from PyPi.
    Thanks again for raising this issue and providing a testcase!

Best Regards,
Matthew

**Closed by mballance** 2020-06-06 17:26 UTC

**Comment by csantosb** [comment] 2020-06-06 22:09
Much better indeed [indeed](https://gitlab.com/ip-vhdl/pyvsc-test/-/jobs/584445305), thanks !
