### ISSUE TITLE
Part-Select issue

### ISSUE THREAD

**Issue by aneels3** [fvutils/pyvsc#120] opened 2021-11-01 15:48 UTC
Hi @mballance 
I am experiencing a part select issue in an if condition while checking the value of a particular slice/range of a `bit_t` type variable.
Error Message:
```bash
Traceback (most recent call last):
  File "/DATA/anil/GitHub/RISC-V/riscv-dv/pygen/pygen_src/test/riscv_instr_cov_test.py", line 212, in <module>
    cov_test.run_phase()
  File "/DATA/anil/GitHub/RISC-V/riscv-dv/pygen/pygen_src/test/riscv_instr_cov_test.py", line 87, in run_phase
    if not self.sample():
  File "/DATA/anil/GitHub/RISC-V/riscv-dv/pygen/pygen_src/test/riscv_instr_cov_test.py", line 147, in sample
    self.instr_cg.sample(instruction)
  File "pygen/pygen_src/riscv_instr_cover_group.py", line 7585, in sample
    if ((instr.binary[1:0] != 3) and (riscv_instr_group_t.RV32C in rcs.supported_isa)):
TypeError: 'int' object is not subscriptable
```
Unfortunately, I was not able to reproduce the above behaviour in the test case.

Due to the unavailability of the test case and to understand the error in more detail.
You can try to reproduce the error at your end by running the below command on this [branch](https://github.com/saurabhsingh-pvips/riscv-dv/tree/rv32fd_debug)
```bash
python3 cov.py --dir fd_cov/ --simulator pyflow --target rv32imafdc --enable_visualization
```

Looking forward to hearing from you on this.

Thanks and Regards,
Anil

**Comment by mballance** [comment] 2021-11-01 22:45
Hi @aneels3,
    Thanks for sharing the branch and instructions for reproducing the issue. The issue occurs because the 'slice' operator requires the class attribute to be of PyVSC class type, but a direct Python assignment replaces the attribute entirely. 
https://github.com/saurabhsingh-pvips/riscv-dv/blob/16b40ec58c2ef3f15bcde78973674bba624d5c19/pygen/pygen_src/test/riscv_instr_cov_test.py#L158-L160

Because Python is a dynamically-typed language, assigning a value to `instruction.trace` with the "equals" operator overwrites the type of the field instead of just setting the field's value. PyVSC coverage works with integer-typed fields in many cases, but using the slice operator requires the field to be a PyVSC type.

The simplest fix is to use `set_val` on the field instead of assigning it directly. I see that the 'pc' field is already being assigned this way. I've tested this in my environment, and it appears to work.

```
        instruction.pc.set_val(get_val(self.trace["pc"], hexa=1))
        instruction.binary.set_val(get_val(self.trace["binary"], hexa=1))
```

Best Regards,
Matthew

**Closed by mballance** 2021-11-01 22:45 UTC

**Comment by aneels3** [comment] 2021-11-02 11:57
Hi @mballance 
Thanks for the help and the explanation.
It's working now.
