### ISSUE TITLE
Support for solve before constraints

### ISSUE THREAD

**Issue by pvipsyash** [fvutils/pyvsc#34] opened 2020-08-17 05:30 UTC
Hi @mballance 

As we know **System Verilog** has **solve before** constraint property, to specify the order of constraint solving. We tried to found some alternatives, but haven't found the solution. So, can we have support for the same in **pyvsc** or some other way to do it?

Thanks & Regards,
Yash

**Comment by mballance** [comment] 2020-08-17 14:34
Hi @pvipsyash,
    Can you share an example of your use-case for solve-before? I'm assuming it's to control distribution across constraint-related variables. A testcase would also be very helpful to be able to validate any implementation.
    This feature, unfortunately, is a fairly major one and will likely take some time. In the meantime, you might try using dist constraints if you just need to fix-up the distribution on some variables.

Best Regards,
Matthew

**Comment by ShraddhaDevaiya** [comment] 2020-08-18 04:44
Hi @mballance ,  
**Solve before** is the constraint property. **solve before** is used inside the constraint block to specify the order of constraint solving. If the variables are dependent, due to the bidirectional nature of constraints value of one variable will influence the value of another variable.
Means if a = b + 5 and a,b are random variables, then constraint on B must solve first. So, for this we can write, **b solve before a**.

Thanks & Regards,
Shraddha Devaiya.

**Comment by mballance** [comment] 2020-08-18 04:52
Hi @ShraddhaDevaiya,
    Yes, I'm familiar with the construct and the description you quote:
https://verificationguide.com/systemverilog/systemverilog-solve-before-constraints/

    My request was for a testcase or use-case example that we could use for validating the implementation, and possibly for finding a short-term alternative solution since solve-before is a somewhat-involved construct to implement. Do you have such a testcase?

Thanks,
Matthew

**Comment by ShraddhaDevaiya** [comment] 2020-08-18 08:44
Hi @mballance ,
Sorry for misinterpreting it. I am working as per your inputs for **solve before** using **weighted distribution** and trying to produce the behavior. Will provide the use-case for this.

Thanks & Regards,
Shraddha Devaiya.

**Comment by ShraddhaDevaiya** [comment] 2020-08-18 11:08
Hi @mballance, I was trying this code for **solve before** constraint using weighted distribution. Following is the code for it : 
```
import vsc

@vsc.randobj
class my_s(object):
    def __init__(self):
        super().__init__()
        self.a = vsc.rand_bit_t(8)
        self.b = vsc.rand_bit_t(8)
        
    @vsc.constraint
    def ab_con(self):
        vsc.dist(self.a, [ 
            vsc.weight(1, 5), 
            vsc.weight(2,2),
            vsc.weight(3,2)])

        with vsc.implies(self.a == 1):
            self.b == 1

item = my_s()

for i in range(10):
    item.randomize()
    print("A = ",item.a,", B = ",item.b)
```
And for this, output is like following : 
```
A =  3 , B =  0
A =  1 , B =  1
A =  1 , B =  1
A =  1 , B =  1
A =  1 , B =  1
A =  3 , B =  7
A =  3 , B =  90
A =  1 , B =  1
A =  1 , B =  1
A =  1 , B =  1
```
Here, we get more occurrences of value **a=1** , but it will not give any other values except specify in weighted distribution constraint. But temporary we can use this.

Thanks & Regards,
Shraddha Devaiya.

**Comment by pvipsyash** [comment] 2020-10-05 04:30
Hi @mballance 

When can we expect support for solve before? without it, every time we need to find some workaround for dependency.

Thanks & Regards,
Yash Patel

**Comment by mballance** [comment] 2020-10-06 14:36
Hi @pvipsyash,
    Apologies for the delay in this, Yash. Supporting solve-before turned out to be a much larger project that I had originally thought. I'll try to get you an update this weekend when I have a bit more time to work on the project.

Best Regards,
Matthew

**Comment by mballance** [comment] 2020-10-12 02:24
Hi @pvipsyash,
    I was able to spend some time on this over the weekend, and believe I'm pretty close to having an implementation ready to release. I have a bit of cleanup still to do, but should be able to get something out this week.

Best Regards,
Matthew

**Comment by pvipsyash** [comment] 2020-10-12 06:30
Hi @mballance 

Thanks for the updates. It will be a great help!

Regards,
Yash Patel

**Comment by mballance** [comment] 2020-10-18 02:02
Hi Yash,
    I've merged support for solve-ordering into PyVSC mainline. Here is an example of using the features:
https://github.com/fvutils/pyvsc/blob/487620ad2ccca6c2327731f20c2665a823971656/ve/unit/test_constraint_solve_order.py#L80-L92

    I'll leave this issue open until you're able to confirm that it works for you.

Best Regards,
Matthew

**Comment by pvipsyash** [comment] 2020-10-22 04:54
Hi @mballance 

Thanks for adding this support. As we need to apply this constraint on list-type as well. I've tried some examples but it is not working.

`
import vsc
from enum import IntEnum, auto

class my_e(IntEnum):
    ZERO = 0
    ONE = auto()
    TWO = auto()

@vsc.randobj
class my_c:
    def __init__(self):
        self.s = 7
        self.a = vsc.randsz_list_t(vsc.rand_uint8_t())
        self.b = vsc.rand_list_t(vsc.enum_t(my_e),5)

    @vsc.constraint
    def my_const(self):
        vsc.solve_order(self.b, self.a)
        self.a.size == self.s

obj = my_c()
for i in range(5):
    obj.randomize()
    print(obj.a, obj.b)
`

Can you look into it?

Thanks & Regards,
Yash

**Comment by pvipsyash** [comment] 2020-10-22 04:59
Hi @mballance 

Thanks for adding this support. As we need to apply this constraint on list-type as well. I've tried a few examples but it is not giving proper output.

![image](https://user-images.githubusercontent.com/66958495/96826665-67b8c180-1451-11eb-82e6-9f9b84479f57.png)

Can you look into this?

Regards,
Yash

**Comment by mballance** [comment] 2020-10-25 22:56
Hi @pvipsyash,
    Thanks for the testcase. Really helped in reproducing the core issue, which involved the unconstrained elements of the arrays not being properly randomized. The 0.2.5 release resolves this issue.
    I'm closing this issue for now. Please open a new issue if you experience other trouble using the solve-order constraint.

Best Regards,
Matthew

**Closed by mballance** 2020-10-25 22:56 UTC
