### ISSUE TITLE
I can't install pyvsc for pypy3.10！

### ISSUE THREAD

**Issue by see01995** [fvutils/pyvsc#198] opened 2023-10-30 06:10 UTC
Hi，

I try to install pyvsc for pypy on Ubuntu 22.04.2 LTS(WSL2).

pypy info:
Python 3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jun 15 2023, 12:39:27)
[PyPy 7.3.12 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]

install command and error report:
~$ pypy -mpip install pyvsc
Collecting pyvsc
  Obtaining dependency information for pyvsc from https://files.pythonhosted.org/packages/ab/ac/c88656a407982b9a60220a67e7823ebb26e4158c42dcb352e3dc7c2ebf1e/pyvsc-0.8.6.6319294550-py2.py3-none-any.whl.metadata
  Using cached pyvsc-0.8.6.6319294550-py2.py3-none-any.whl.metadata (739 bytes)
Collecting pyboolector>=3.2.2 (from pyvsc)
  Using cached PyBoolector-3.2.3.20230913.1.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/c6/11/31a75fe4560de79c12f45ac7cafb5858b25699f24ce0ee03e89c22e1c1fd/PyBoolector-3.2.3.20230913.1.tar.gz (from https://pypi.org/simple/pyboolector/): Requested pyboolector>=3.2.2 from https://files.pythonhosted.org/packages/c6/11/31a75fe4560de79c12f45ac7cafb5858b25699f24ce0ee03e89c22e1c1fd/PyBoolector-3.2.3.20230913.1.tar.gz (from pyvsc) has inconsistent version: expected '3.2.3.20230913.1', but metadata has '3.2.3'
  Using cached PyBoolector-3.2.3.20230911.5.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/b4/6c/774fd4130d45cec37468b8222f08afc9260f3abafd47f3fa47b3cf2de34f/PyBoolector-3.2.3.20230911.5.tar.gz (from https://pypi.org/simple/pyboolector/): Requested pyboolector>=3.2.2 from https://files.pythonhosted.org/packages/b4/6c/774fd4130d45cec37468b8222f08afc9260f3abafd47f3fa47b3cf2de34f/PyBoolector-3.2.3.20230911.5.tar.gz (from pyvsc) has inconsistent version: expected '3.2.3.20230911.5', but metadata has '3.2.3'
  Using cached PyBoolector-3.2.2.20230911.3.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/94/01/6a7c8b476eefdabdeeaac30bf9227c55d6ccb0638b2573a3fe3ebff1bc4f/PyBoolector-3.2.2.20230911.3.tar.gz (from https://pypi.org/simple/pyboolector/): Requested pyboolector>=3.2.2 from https://files.pythonhosted.org/packages/94/01/6a7c8b476eefdabdeeaac30bf9227c55d6ccb0638b2573a3fe3ebff1bc4f/PyBoolector-3.2.2.20230911.3.tar.gz (from pyvsc) has inconsistent version: expected '3.2.2.20230911.3', but metadata has '3.2.2'
  Using cached PyBoolector-3.2.2.20230110.4.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-46rpu5yi/pyboolector_7bda46620ec045bf9a83469dfc11971f/setup.py", line 14, in <module>
          with open(cmakelists_txt, "r") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-46rpu5yi/CMakeLists.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mballance** [comment] 2023-10-30 13:58
Hmm... Unfortunately, it looks like there are two overlapping issues here. Have you been able to install PyBoolector for PyPy previously?
The first error I see involves a version mismatch. You might be able to work around this issue passing `--use-deprecated=legacy-resolver`, as suggested by this issue: (https://github.com/pypa/pip/issues/9203).
PyBoolector doesn't provide a pre-built wheel for PyPy, so it will attempt to build the wheel from source. This assumes that you have installed Boolector locally by hand.

I'll look into both issues. However, it would be useful to know whether this is a regression (ie you used to be able to install in PyPy) vs this being an error you get when trying PyPy with PyVSC/PyBoolector for the first time.

Thanks,
Matthew

**Comment by see01995** [comment] 2023-10-31 01:08
I try to install PyBoolector, it report the same error.
I will try your suggest, thanks.

$ pypy -mpip install PyBoolector
Collecting PyBoolector
  Using cached PyBoolector-3.2.3.20230913.1.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/c6/11/31a75fe4560de79c12f45ac7cafb5858b25699f24ce0ee03e89c22e1c1fd/PyBoolector-3.2.3.20230913.1.tar.gz (from https://pypi.org/simple/pyboolector/): Requested PyBoolector from https://files.pythonhosted.org/packages/c6/11/31a75fe4560de79c12f45ac7cafb5858b25699f24ce0ee03e89c22e1c1fd/PyBoolector-3.2.3.20230913.1.tar.gz has inconsistent version: expected '3.2.3.20230913.1', but metadata has '3.2.3'
  Using cached PyBoolector-3.2.3.20230911.5.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/b4/6c/774fd4130d45cec37468b8222f08afc9260f3abafd47f3fa47b3cf2de34f/PyBoolector-3.2.3.20230911.5.tar.gz (from https://pypi.org/simple/pyboolector/): Requested PyBoolector from https://files.pythonhosted.org/packages/b4/6c/774fd4130d45cec37468b8222f08afc9260f3abafd47f3fa47b3cf2de34f/PyBoolector-3.2.3.20230911.5.tar.gz has inconsistent version: expected '3.2.3.20230911.5', but metadata has '3.2.3'
  Using cached PyBoolector-3.2.2.20230911.3.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/94/01/6a7c8b476eefdabdeeaac30bf9227c55d6ccb0638b2573a3fe3ebff1bc4f/PyBoolector-3.2.2.20230911.3.tar.gz (from https://pypi.org/simple/pyboolector/): Requested PyBoolector from https://files.pythonhosted.org/packages/94/01/6a7c8b476eefdabdeeaac30bf9227c55d6ccb0638b2573a3fe3ebff1bc4f/PyBoolector-3.2.2.20230911.3.tar.gz has inconsistent version: expected '3.2.2.20230911.3', but metadata has '3.2.2'
  Using cached PyBoolector-3.2.2.20230110.4.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j6d85ori/pyboolector_8cda86cecce041eab14e7f8c9284479b/setup.py", line 14, in <module>
          with open(cmakelists_txt, "r") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-j6d85ori/CMakeLists.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by see01995** [comment] 2023-11-01 00:55
i modified build.sh of PyBoolector, and gen whl:

```bash
#!/usr/bin/env bash
set -e -o pipefail

mkdir -p ./build
cd ./build

echo "Hello from PyPi build.sh"

BUILD_DIR=`pwd`
N_CORES=`nproc`

#test -n "$PYTHON_VERSIONS" || { echo PYTHON_VERSIONS must be set.; exit 1; }

echo "copy start"

cp -r ../boolector .

echo "copy end"

# Setup dependencies
cd boolector
#/bin/sh ./contrib/setup-btor2tools.sh
#/bin/sh ./contrib/setup-cadical.sh
#/bin/sh ./contrib/setup-lingeling.sh
./contrib/setup-btor2tools.sh
./contrib/setup-cadical.sh
./contrib/setup-lingeling.sh

#********************************************************************
#* boolector
#********************************************************************
cd ${BUILD_DIR}

cd boolector

#./configure.sh --python --shared --prefix output
./configure.sh --python --shared --prefix /usr/local
cd build

echo "make"

make -j${N_CORES}

make install

#********************************************************************
#* pyboolector
#********************************************************************

cd ${BUILD_DIR}
rm -rf pyboolector

export CC=gcc
export CXX=g++

# Specify path to CmakeLists.txt so setup.py can extract the version
export CMAKELISTS_TXT=${BUILD_DIR}/boolector/CMakeLists.txt

cp -r ${BUILD_DIR}/boolector/pypi pyboolector

# Prepare the artifact directory.
rm -rf ${BUILD_DIR}/boolector/result
mkdir -p ${BUILD_DIR}/boolector/result

# Grab the main license file
cp ${BUILD_DIR}/boolector/COPYING pyboolector/LICENSE

cd pyboolector

#for py in $PYTHON_VERSIONS; do
#  python=$(ls /opt/python/${py}-*/bin/python)
#  echo "Python: ${python}"
#  ${python} -m pip install cython wheel
#  cd ${BUILD_DIR}/pyboolector
#  rm -rf src
#  cp -r ${BUILD_DIR}/boolector/src/api/python src
#  sed -i -e 's/override//g' \
#     -e 's/noexcept/_GLIBCXX_USE_NOEXCEPT/g' \
#     -e 's/\(BoolectorException (const.*\)/\1\n    virtual ~BoolectorException() _GLIBCXX_USE_NOEXCEPT {}/' \
#       src/pyboolector_abort.cpp
#  mkdir -p src/utils
#  cp ${BUILD_DIR}/boolector/src/*.h src
#  cp ${BUILD_DIR}/boolector/src/utils/*.h src/utils
#  $python ./src/mkenums.py ./src/btortypes.h ./src/pyboolector_enums.pxd
#  $python setup.py sdist bdist_wheel
#done

echo "python"

  python=/usr/bin/pypy
  echo "Python: ${python}"
  ${python} -m pip install cython wheel
  cd ${BUILD_DIR}/pyboolector
  rm -rf src
  cp -r ${BUILD_DIR}/boolector/src/api/python src
  sed -i -e 's/override//g' \
     -e 's/noexcept/_GLIBCXX_USE_NOEXCEPT/g' \
     -e 's/\(BoolectorException (const.*\)/\1\n    virtual ~BoolectorException() _GLIBCXX_USE_NOEXCEPT {}/' \
       src/pyboolector_abort.cpp
  mkdir -p src/utils
  cp ${BUILD_DIR}/boolector/src/*.h src
  cp ${BUILD_DIR}/boolector/src/utils/*.h src/utils
  $python ./src/mkenums.py ./src/btortypes.h ./src/pyboolector_enums.pxd
  $python setup.py sdist bdist_wheel

# Copy the source distribution into the artifact directory.
cp dist/*.tar.gz ${BUILD_DIR}/boolector/result

# Repair wheels and place them into the artifact directory.
for whl in dist/*.whl; do
  auditwheel repair --plat manylinux_2_24_x86_64 --wheel-dir ${BUILD_DIR}/boolector/result/dist $whl
done
```

**Comment by mballance** [comment] 2024-03-15 23:16
This issue has been resolved. Belatedly-closing the ticket to reflect that

**Closed by mballance** 2024-03-15 23:16 UTC
